#ifndef __EXIT_STATUS_H__
#define __EXIT_STATUS_H__

#define INVALID_OPTION 1
#define INVALID_ARGV_FORMAT 2
#define ARGV_TOO_SHORT 3
#define DATA_FILE_NOT_FOUND 4
#define DATA_FILE_EMPTY 5
#define TEMPERATURE_MINUS 6
#define PRECISION_NON_POSITIVE 7
#define VOXEL_NOT_FOUND 8

#endif
